name: "Setup Project"
description: "Common setup steps for CI"

outputs:
  version:
    description: "Extracted version"
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Cached konan
      uses: actions/cache@v4.2.3
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

    - name: Prepare JDK
      uses: actions/setup-java@v5.2.0
      with:
        java-version: 21
        distribution: temurin
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Extract Version from Tag
      id: version
      shell: bash
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        VERSION=${TAG_NAME#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Export version
      shell: bash
      run: echo "version=${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT