on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup project
        id: setup
        uses: ./.github/actions/setup-project

      - name: Prepare test access environment
        env:
          ACCESS_CSV: ${{ secrets.ACCESS_CSV }}
        run: |
          cat <<EOF > ${GITHUB_WORKSPACE}/library/access.csv
          $ACCESS_CSV
          EOF

      - name: Run tests
        run: ./gradlew jvmTest -Pversion=${{ steps.setup.outputs.version }}

  build:
    runs-on: macos-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup project
        id: setup
        uses: ./.github/actions/setup-project

      - name: Publish
        run: ./gradlew publish -Pversion=${{ steps.setup.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}